### ISSUE TITLE
Keep awareness active when changing chats

### ISSUE THREAD

**Issue by german-e-mas** [ekumenlabs/telegram-tt#3]
Currently, when the chat changes, awareness is disabled.

We should preserve the awareness on the chat it was activated on.

**Comment by mattborghi** [comment]
> We should preserve the awareness on the chat it was activated on.

That's fine for me. The only issue I see is that enable-awareness button should always be clicked inside Ekumen's group chat, because enabling it from any other chat would enter another room.

Preserving awareness might make a user think that awareness can be activated from any chat and if you do that you will only see yourself. But that's my point of view given I didn't use the previous version.

**Comment by german-e-mas** [comment]
That's true. We can restrict enabling awareness only for the Ekumen group, and that will cut potential corner cases. We can have it's ID as an env var, and check against it. What do you think?

**Comment by mattborghi** [comment]
Yeah I like that idea. I will try to make it work.
